-- Seed catalog
BEGIN;

INSERT INTO service_categories (id, name, sort_order) VALUES (1, 'Design', 1) ON CONFLICT (name) DO NOTHING;
INSERT INTO service_categories (id, name, sort_order) VALUES (2, 'Permits & Licensing', 2) ON CONFLICT (name) DO NOTHING;
INSERT INTO service_categories (id, name, sort_order) VALUES (3, 'Surveying & Land', 3) ON CONFLICT (name) DO NOTHING;
INSERT INTO service_categories (id, name, sort_order) VALUES (4, 'Supervision & Project Management', 4) ON CONFLICT (name) DO NOTHING;
INSERT INTO service_categories (id, name, sort_order) VALUES (5, 'Inspections & Technical Reports', 5) ON CONFLICT (name) DO NOTHING;
INSERT INTO service_categories (id, name, sort_order) VALUES (6, 'MEP & Specialized Systems', 6) ON CONFLICT (name) DO NOTHING;
INSERT INTO service_categories (id, name, sort_order) VALUES (7, 'Insurance & Compliance', 7) ON CONFLICT (name) DO NOTHING;
INSERT INTO service_categories (id, name, sort_order) VALUES (8, 'Engineering Studies', 8) ON CONFLICT (name) DO NOTHING;
INSERT INTO service_categories (id, name, sort_order) VALUES (9, 'Operations, Maintenance & Facility Management', 9) ON CONFLICT (name) DO NOTHING;
INSERT INTO service_categories (id, name, sort_order) VALUES (10, 'Advisory & Engineering Arbitration', 10) ON CONFLICT (name) DO NOTHING;

INSERT INTO service_packages (id, slug, name, description, categories_included, sort_order) VALUES (1, 'build-my-villa', 'Build My Villa', 'End-to-end path from design to villa handover with supervision', 'Design + Permits + Supervision + Inspections + Insurance', 1) ON CONFLICT (slug) DO NOTHING;
INSERT INTO service_packages (id, slug, name, description, categories_included, sort_order) VALUES (2, 'design-to-permit', 'Design to Permit', 'Integrated design package ending in a building permit', 'Design + Permits + Surveying', 2) ON CONFLICT (slug) DO NOTHING;
INSERT INTO service_packages (id, slug, name, description, categories_included, sort_order) VALUES (3, 'fast-permit', 'Fast Permit', 'Quick building-permit issuance on a ready design', 'Permits', 3) ON CONFLICT (slug) DO NOTHING;
INSERT INTO service_packages (id, slug, name, description, categories_included, sort_order) VALUES (4, 'renovate-&-expand', 'Renovate & Expand', 'Renovate or extend an existing building with required approvals', 'Interior design + Renovation/demolition permits + Inspections', 4) ON CONFLICT (slug) DO NOTHING;
INSERT INTO service_packages (id, slug, name, description, categories_included, sort_order) VALUES (5, 'legalize-my-building', 'Legalize My Building', 'Regularize a non-compliant building and correct its status', 'Surveying + Permit amendment + Safety reports', 5) ON CONFLICT (slug) DO NOTHING;
INSERT INTO service_packages (id, slug, name, description, categories_included, sort_order) VALUES (6, 'design-studio', 'Design Studio', 'Interior/architectural design and visual experience services', 'Interior + Architectural + Automation + Sustainability', 6) ON CONFLICT (slug) DO NOTHING;
INSERT INTO service_packages (id, slug, name, description, categories_included, sort_order) VALUES (7, 'standalone-add-on', 'Standalone / Add-on', 'Services requested separately or added onto a package', 'Mixed across categories', 7) ON CONFLICT (slug) DO NOTHING;

INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (1, 'Concept / schematic design', 1, 'Office + individual engineer', 'office_or_individual', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (2, 'Architectural design', 1, 'Office + individual engineer', 'office_or_individual', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (3, 'Facade design', 1, 'Office + individual engineer', 'office_or_individual', 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (4, 'Working drawings', 1, 'Office + individual engineer', 'office_or_individual', 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (5, 'Structural design', 1, 'Office + individual engineer', 'office_or_individual', 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (6, 'Electrical systems design', 1, 'Office + individual engineer', 'office_or_individual', 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (7, 'Plumbing, drainage & water-supply design', 1, 'Office + individual engineer', 'office_or_individual', 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (8, 'Interior design & décor', 1, 'Office + individual engineer', 'office_or_individual', 8) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (9, 'Landscape design', 1, 'Office + individual engineer', 'office_or_individual', 9) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (10, 'Lighting design', 1, 'Office + individual engineer', 'office_or_individual', 10) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (11, 'Acoustic design', 1, 'Office + individual engineer', 'office_or_individual', 11) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (12, 'Kitchen & cabinetry design', 1, 'Office + individual engineer', 'office_or_individual', 12) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (13, 'Furniture & joinery design', 1, 'Office + individual engineer', 'office_or_individual', 13) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (14, 'Swimming-pool design', 1, 'Office + individual engineer', 'office_or_individual', 14) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (15, '3D architectural rendering', 1, 'Office + individual engineer', 'office_or_individual', 15) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (16, 'BIM modeling & quantity take-off', 1, 'Office + individual engineer', 'office_or_individual', 16) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (17, 'Value engineering', 1, 'Office + individual engineer', 'office_or_individual', 17) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (18, 'Shop-drawings review', 1, 'Office + individual engineer', 'office_or_individual', 18) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (19, 'As-built drawings', 1, 'Office + individual engineer', 'office_or_individual', 19) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (20, 'Deep foundations & piling design', 1, 'Office + individual engineer', 'office_or_individual', 20) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (21, 'Shoring / excavation-support design', 1, 'Office + individual engineer', 'office_or_individual', 21) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (22, 'Retaining-wall design', 1, 'Office + individual engineer', 'office_or_individual', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (23, 'Dewatering design', 1, 'Office + individual engineer', 'office_or_individual', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (24, 'Roads & internal pavement design', 1, 'Office + individual engineer', 'office_or_individual', 24) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (25, 'Site infrastructure design', 1, 'Office + individual engineer', 'office_or_individual', 25) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (26, 'External water & sewage network design', 1, 'Office + individual engineer', 'office_or_individual', 26) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (27, 'Street-lighting design', 1, 'Office + individual engineer', 'office_or_individual', 27) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (28, 'Heritage building restoration design', 1, 'Specialized office', 'specialized_office', 28) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (29, 'Digital twin of the building', 1, 'Office + individual engineer', 'office_or_individual', 29) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (30, 'Virtual walkthroughs (VR/AR)', 1, 'Office + individual engineer', 'office_or_individual', 30) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (31, 'Building permit issuance (Balady)', 2, 'Engineering office', 'engineering_office', 31) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (32, 'Demolition permit', 2, 'Engineering office', 'engineering_office', 32) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (33, 'Fencing permit', 2, 'Engineering office', 'engineering_office', 33) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (34, 'Renovation & modification permit', 2, 'Engineering office', 'engineering_office', 34) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (35, 'Excavation permit', 2, 'Engineering office', 'engineering_office', 35) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (36, 'Construction completion certificate', 2, 'Engineering office', 'engineering_office', 36) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (37, 'Permit amendment / renewal', 2, 'Engineering office', 'engineering_office', 37) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (38, 'Change of use (residential/commercial)', 2, 'Engineering office', 'engineering_office', 38) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (39, 'Signage & advertising permits', 2, 'Engineering office', 'engineering_office', 39) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (40, 'Utility connection permits (power/water)', 2, 'Engineering office', 'engineering_office', 40) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (41, 'Civil Defense (safety) approval', 2, 'Engineering office', 'engineering_office', 41) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (42, 'Environmental permits', 2, 'Engineering office', 'engineering_office', 42) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (43, 'Subdivision approval / plot sketch', 2, 'Engineering office', 'engineering_office', 43) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (44, 'Sidewalk-cut / road-occupancy permit', 2, 'Engineering office', 'engineering_office', 44) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (45, 'Objections & exemptions handling', 2, 'Engineering office', 'engineering_office', 45) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (46, 'GACA height clearance', 2, 'Engineering office', 'engineering_office', 46) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (47, 'Heritage Commission approval', 2, 'Engineering office', 'engineering_office', 47) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (48, 'Drawing attestation & stamping', 2, 'Engineering office', 'engineering_office', 48) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (49, 'No-objection certificate (NOC)', 2, 'Engineering office', 'engineering_office', 49) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (50, 'Topographic survey', 3, 'Office + individual engineer', 'office_or_individual', 50) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (51, 'Coordinates & boundary determination', 3, 'Office + individual engineer', 'office_or_individual', 51) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (52, 'Setbacks & levels determination', 3, 'Office + individual engineer', 'office_or_individual', 52) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (53, 'Deed transfer / merge / subdivision', 3, 'Engineering office', 'engineering_office', 53) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (54, 'Cadastral survey', 3, 'Engineering office', 'engineering_office', 54) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (55, 'Verification survey of buildings', 3, 'Office + individual engineer', 'office_or_individual', 55) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (56, 'Earthwork (cut & fill) calculations', 3, 'Office + individual engineer', 'office_or_individual', 56) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (57, 'Aerial (drone) survey', 3, 'Specialized office', 'specialized_office', 57) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (58, 'Deed-correction support', 3, 'Engineering office', 'engineering_office', 58) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (59, 'GIS services', 3, 'Engineering office', 'engineering_office', 59) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (60, '3D laser scanning (Scan-to-BIM)', 3, 'Specialized office', 'specialized_office', 60) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (61, 'Construction supervision', 4, 'Engineering office', 'engineering_office', 61) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (62, 'Construction project management (PM)', 4, 'Office + individual engineer', 'office_or_individual', 62) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (63, 'Resident engineer', 4, 'Office + individual engineer', 'office_or_individual', 63) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (64, 'Quality control & compliance', 4, 'Office + individual engineer', 'office_or_individual', 64) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (65, 'Quantity surveying (QS)', 4, 'Office + individual engineer', 'office_or_individual', 65) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (66, 'Contract management & contractor follow-up', 4, 'Office + individual engineer', 'office_or_individual', 66) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (67, 'Scheduling & planning', 4, 'Office + individual engineer', 'office_or_individual', 67) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (68, 'Tender management & contractor selection', 4, 'Office + individual engineer', 'office_or_individual', 68) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (69, 'Site safety supervision', 4, 'Specialized office', 'specialized_office', 69) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (70, 'Handover & snagging inspection', 4, 'Office + individual engineer', 'office_or_individual', 70) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (71, 'Periodic progress reports', 4, 'Office + individual engineer', 'office_or_individual', 71) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (72, 'Commissioning', 4, 'Specialized office', 'specialized_office', 72) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (73, 'O&M manuals preparation', 4, 'Office + individual engineer', 'office_or_individual', 73) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (74, 'Tender documents & BoQ preparation', 4, 'Office + individual engineer', 'office_or_individual', 74) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (75, 'Soil investigation & geotechnical boring', 5, 'Specialized office', 'specialized_office', 75) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (76, 'Concrete & materials testing', 5, 'Specialized office', 'specialized_office', 76) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (77, 'Non-destructive testing (NDT)', 5, 'Specialized office', 'specialized_office', 77) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (78, 'Structural safety assessment', 5, 'Office + individual engineer', 'office_or_individual', 78) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (79, 'Retrofit / strengthening assessment', 5, 'Office + individual engineer', 'office_or_individual', 79) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (80, 'Crack & settlement monitoring', 5, 'Office + individual engineer', 'office_or_individual', 80) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (81, 'Leak & waterproofing detection', 5, 'Office + individual engineer', 'office_or_individual', 81) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (82, 'Thermal imaging', 5, 'Specialized office', 'specialized_office', 82) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (83, 'Pre-purchase property inspection', 5, 'Office + individual engineer', 'office_or_individual', 83) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (84, 'Facade inspection', 5, 'Office + individual engineer', 'office_or_individual', 84) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (85, 'Periodic elevator inspection', 5, 'Specialized office', 'specialized_office', 85) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (86, 'Fire & safety systems inspection', 5, 'Specialized office', 'specialized_office', 86) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (87, 'Technical damage / dispute reports (expert)', 5, 'Office + individual engineer', 'office_or_individual', 87) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (88, 'Energy audit', 5, 'Office + individual engineer', 'office_or_individual', 88) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (89, 'Asset condition assessment', 5, 'Office + individual engineer', 'office_or_individual', 89) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (90, 'HVAC design', 6, 'Office + individual engineer', 'office_or_individual', 90) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (91, 'Central AC systems', 6, 'Office + individual engineer', 'office_or_individual', 91) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (92, 'Fire-fighting & safety systems design', 6, 'Specialized office', 'specialized_office', 92) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (93, 'Electrical load studies & connection', 6, 'Office + individual engineer', 'office_or_individual', 93) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (94, 'Solar energy systems', 6, 'Office + individual engineer', 'office_or_individual', 94) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (95, 'Generators & backup power', 6, 'Office + individual engineer', 'office_or_individual', 95) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (96, 'Extra-low-voltage (ELV) systems', 6, 'Office + individual engineer', 'office_or_individual', 96) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (97, 'Surveillance & security systems (CCTV)', 6, 'Office + individual engineer', 'office_or_individual', 97) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (98, 'Automation & smart building (BMS)', 6, 'Office + individual engineer', 'office_or_individual', 98) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (99, 'Elevators & vertical-transport engineering', 6, 'Specialized office', 'specialized_office', 99) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (100, 'Water-treatment systems', 6, 'Office + individual engineer', 'office_or_individual', 100) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (101, 'Irrigation systems', 6, 'Office + individual engineer', 'office_or_individual', 101) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (102, 'Central gas systems', 6, 'Specialized office', 'specialized_office', 102) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (103, 'Pumping & sewage-treatment stations', 6, 'Specialized office', 'specialized_office', 103) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (104, 'Latent-defects insurance', 7, 'Office / insurer', 'office_or_insurer', 104) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (105, 'Contractor all-risks insurance (CAR)', 7, 'Office / insurer', 'office_or_insurer', 105) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (106, 'Saudi Building Code (SBC) compliance check', 7, 'Office + individual engineer', 'office_or_individual', 106) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (107, 'Green building certification (Mostadam)', 7, 'Office + individual engineer', 'office_or_individual', 107) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (108, 'LEED consultancy', 7, 'Office + individual engineer', 'office_or_individual', 108) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (109, 'Sustainability & energy-efficiency consulting', 7, 'Office + individual engineer', 'office_or_individual', 109) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (110, 'Universal accessibility compliance', 7, 'Office + individual engineer', 'office_or_individual', 110) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (111, 'Municipal compliance audit', 7, 'Office + individual engineer', 'office_or_individual', 111) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (112, 'Warranties & handover documentation', 7, 'Office + individual engineer', 'office_or_individual', 112) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (113, 'Economic feasibility study', 8, 'Office + individual engineer', 'office_or_individual', 113) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (114, 'Technical feasibility study', 8, 'Office + individual engineer', 'office_or_individual', 114) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (115, 'Highest & best use study', 8, 'Office + individual engineer', 'office_or_individual', 115) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (116, 'Site-selection study', 8, 'Office + individual engineer', 'office_or_individual', 116) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (117, 'Project brief & pre-design study', 8, 'Office + individual engineer', 'office_or_individual', 117) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (118, 'Geotechnical & soil-mechanics study', 8, 'Specialized office', 'specialized_office', 118) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (119, 'Structural analysis study', 8, 'Office + individual engineer', 'office_or_individual', 119) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (120, 'Seismic study', 8, 'Office + individual engineer', 'office_or_individual', 120) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (121, 'Thermal-load & energy-efficiency study', 8, 'Office + individual engineer', 'office_or_individual', 121) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (122, 'Daylighting study', 8, 'Office + individual engineer', 'office_or_individual', 122) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (123, 'Acoustic & noise study', 8, 'Office + individual engineer', 'office_or_individual', 123) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (124, 'Environmental impact assessment (EIA)', 8, 'Specialized office', 'specialized_office', 124) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (125, 'Hydrology & flood-mitigation study', 8, 'Specialized office', 'specialized_office', 125) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (126, 'Stormwater drainage study', 8, 'Office + individual engineer', 'office_or_individual', 126) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (127, 'Traffic impact study', 8, 'Specialized office', 'specialized_office', 127) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (128, 'Vertical-transport (elevator) study', 8, 'Specialized office', 'specialized_office', 128) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (129, 'Construction-waste management study', 8, 'Office + individual engineer', 'office_or_individual', 129) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (130, 'Cost & budget estimation study', 8, 'Office + individual engineer', 'office_or_individual', 130) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (131, 'Risk assessment study', 8, 'Office + individual engineer', 'office_or_individual', 131) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (132, 'Sustainability & green-building study', 8, 'Office + individual engineer', 'office_or_individual', 132) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (133, 'Corrosion-protection study', 8, 'Specialized office', 'specialized_office', 133) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (134, 'Wind-load study', 8, 'Specialized office', 'specialized_office', 134) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (135, 'Facility management (FM)', 9, 'Specialized office', 'specialized_office', 135) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (136, 'Preventive maintenance planning', 9, 'Office + individual engineer', 'office_or_individual', 136) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (137, 'MEP operations & maintenance', 9, 'Specialized office', 'specialized_office', 137) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (138, 'Building performance optimization', 9, 'Office + individual engineer', 'office_or_individual', 138) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (139, 'Energy & water consumption management', 9, 'Office + individual engineer', 'office_or_individual', 139) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (140, 'Engineering arbitration', 10, 'Specialized office', 'specialized_office', 140) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (141, 'Expert witness / court testimony', 10, 'Office + individual engineer', 'office_or_individual', 141) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (142, 'Independent design review (peer review)', 10, 'Office + individual engineer', 'office_or_individual', 142) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (143, 'Engineering contract drafting & review', 10, 'Office + individual engineer', 'office_or_individual', 143) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (144, 'Construction claims & variations management', 10, 'Office + individual engineer', 'office_or_individual', 144) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (145, 'General technical advisory', 10, 'Office + individual engineer', 'office_or_individual', 145) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (146, 'Second technical opinion', 10, 'Office + individual engineer', 'office_or_individual', 146) ON CONFLICT (id) DO NOTHING;
INSERT INTO engineering_services (id, name, category_id, provider, provider_type, sort_order) VALUES (147, 'Property valuation', 10, 'Specialized office', 'specialized_office', 147) ON CONFLICT (id) DO NOTHING;

INSERT INTO service_package_items (service_id, package_id) VALUES (1, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (1, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (1, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (2, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (2, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (2, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (3, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (3, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (4, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (4, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (5, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (5, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (6, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (6, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (7, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (7, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (8, 4) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (8, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (9, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (9, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (10, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (11, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (11, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (12, 4) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (12, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (13, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (14, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (14, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (14, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (15, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (15, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (16, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (16, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (17, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (17, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (18, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (18, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (19, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (19, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (20, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (21, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (22, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (23, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (24, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (24, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (25, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (25, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (26, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (26, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (27, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (27, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (28, 4) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (28, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (28, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (29, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (29, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (30, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (30, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (31, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (31, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (31, 3) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (32, 4) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (32, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (33, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (34, 4) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (35, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (35, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (36, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (37, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (38, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (38, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (39, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (40, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (40, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (41, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (41, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (42, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (43, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (44, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (45, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (45, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (46, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (46, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (47, 4) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (47, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (47, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (48, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (48, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (48, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (49, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (49, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (50, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (50, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (51, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (51, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (52, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (53, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (54, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (54, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (55, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (56, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (56, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (57, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (58, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (58, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (59, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (60, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (60, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (61, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (62, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (63, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (64, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (65, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (65, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (65, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (66, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (67, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (67, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (68, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (68, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (69, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (70, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (70, 4) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (71, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (72, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (73, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (73, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (74, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (74, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (74, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (75, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (75, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (76, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (77, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (77, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (78, 4) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (78, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (79, 4) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (79, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (80, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (80, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (81, 4) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (81, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (82, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (83, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (84, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (85, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (86, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (87, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (88, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (89, 4) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (89, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (89, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (90, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (90, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (91, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (91, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (92, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (93, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (94, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (95, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (96, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (96, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (97, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (97, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (98, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (98, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (99, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (99, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (100, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (101, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (101, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (101, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (102, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (102, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (103, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (104, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (105, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (105, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (106, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (106, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (107, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (107, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (108, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (109, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (109, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (110, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (110, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (111, 5) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (111, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (112, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (113, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (114, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (115, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (116, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (117, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (117, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (117, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (118, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (118, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (119, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (119, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (120, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (120, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (121, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (121, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (122, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (122, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (123, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (123, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (124, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (125, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (125, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (126, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (126, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (127, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (128, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (129, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (130, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (130, 2) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (130, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (131, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (131, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (132, 6) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (132, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (133, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (134, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (135, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (136, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (137, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (138, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (139, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (140, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (141, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (142, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (142, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (143, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (143, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (144, 1) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (144, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (145, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (146, 7) ON CONFLICT DO NOTHING;
INSERT INTO service_package_items (service_id, package_id) VALUES (147, 7) ON CONFLICT DO NOTHING;
COMMIT;